---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: false
configure_sudoers: false
configure_dock: false
configure_vscode: true

dockitems_remove:
# - Launchpad
  - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/fabianotessarolo/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .tmux.conf

homebrew_installed_packages:
  - zsh
  - git
  - node
  - wget
  - fzf
  - tmux

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-fira-code
  - font-fira-mono
  - font-fira-code-nerd-font
  - visual-studio-code
  - iterm2

homedir: "~"


iterm2_dynamic_profiles_local: ['itermProfile.json']
iterm2_preferences_custom_folder: ""
iterm2_default_profile_guid: "DFB89A5E-1958-4BA9-9859-8DE1F8146B64"
iterm2_shell_integration: yes

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
# mas_installed_apps:
#   - { id: 443987910, name: "1Password" }
#   - { id: 498486288, name: "Quick Resizer" }
#   - { id: 557168941, name: "Tweetbot" }
#   - { id: 497799835, name: "Xcode" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

visual_studio_code_extensions:
  - aaronthomas.vscode-snazzy-operator
  - PKief.material-icon-theme

visual_studio_code_settings_overwrite: true

visual_studio_code_settings: {
  "editor.fontFamily": "FiraCode Nerd Font",
  "extensions.ignoreRecommendations": true,
  "editor.minimap.enabled": false,
  "editor.renderWhitespace": "all",
  "workbench.sideBar.location": "left",
  "workbench.statusBar.visible": true,
  "editor.fontLigatures": true,
  "files.autoSave": "onFocusChange",
  "editor.cursorSmoothCaretAnimation": true,
  "editor.fontSize": 12,
  "editor.formatOnPaste": true,
  "workbench.colorTheme": "Snazzy Operator",
  "workbench.iconTheme": "material-icon-theme",
  "editor.rulers": [80, 100, 120],
}
