---
# - name: Install Fuzzy Finde
#   command: "$(brew --prefix)/opt/fzf/install"

- name: clone oh-my-zsh for users
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '{{ homedir }}/.oh-my-zsh'
    depth: 1
    clone: yes
    update: yes

- name: set permissions of oh-my-zsh for users
  file:
    path: '{{ homedir }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: yes

- name: Set default sheell
  command: 'chsh -s /bin/zsh {{ ansible_user_id }} '
  become: true
